spring.application.name=springAI

spring.ai.openai.api-key: ${SPRING_OPEN_AI_KEY}
spring.ai.openai.organization-id: ${SPRING_OPEN_AI_ORG_ID}
spring.ai.openai.project-id: ${SPRING_OPEN_AI_PROJECT_ID}
#spring.ai.openai.chat.options.model=gpt-4o

logging.level.org.springframework.web=debug

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/bdcs
spring.datasource.username=postgres


spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.jpa.show-sql=true